### ISSUE TITLE
Code to download and import the seed beetle data

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/examples#3]
Once the project is tracked by Poetry and has the necessary things installed, the next steps are to:

- [x] Create a new Python file in the `male-seed-beetle/scripts/` folder called `download-data.py`
- [x] Write Python code to use the Dryad link to the raw data, download it to the local computer, and save it in `male-seed-beetle/data-raw/` folder with the file name `data.csv`.
- [x] #10
- [x] In the `male-seed-beetle/scripts/convert-with-core.py` write Python code to import the `data-raw/data.csv` data into Python.

**Comment by K-Beicher** [comment]
Unfortunately Dryad stops automatic downloads from their website, so I created a second script which will ask if you want to load your data from a url or a folder.

**Comment by K-Beicher** [comment]
in the import of data.csv into python we could also use the pathlib to determine the folder. It would apparently look something like this:

from pathlib import Path

file_path = Path(__file__).parent / '../raw-data/data.csv'
file_path = file_path.resolve()

df = pl.read_csv(file_path)

**Comment by K-Beicher** [comment]
Assumptions made to write the download-data.py file.

When the folder structure for a resource is created it contains a data-raw folder with a .gitignore file in it.

The data-raw folder is at the same level in the folder structure as the scripts folder.

The url given won't result in 403 Forbidden, which means that automatic downloads are prevented.
